### ISSUE TITLE
Recommended commenting method? 

### ISSUE THREAD

**Issue by evesala** [open-campaign-logger/generator-library#1]
As the JSON format does not have an official syntax for comments, is there a recommended method for adding notes (explanations, development ideas, issues, etc.) to the tables? 

Something that would be included in the file itself would be much more usable than just commit notes.

**Comment by JochenLinnemann** [comment]
We could easily add an "explanation" property of type string to generators and tables. This shouldn't interfere with the generator.

**Comment by evesala** [comment]
That would be great! Explanations could be useful also for storing meta data, such as date and version notes.

**Comment by JochenLinnemann** [comment]
I just created a branch and added a file to try out and show-case new format extensions: https://github.com/open-campaign-logger/generator-library/blob/extended-file-format/json/_file-format.json

Please feel free to add your thoughts there, too.

**Comment by evesala** [comment]
Have been successfully using *explanation* (as well as several other metadata properties) for some time now. Thanks!
