### ISSUE TITLE
Increase table editor window size in the Web app

### ISSUE THREAD

**Issue by evesala** [open-campaign-logger/generator-library#20]
Could the table editor window (Options > Manage Custom Generators) in the Web app be bigger? Perhaps the window could be dynamically scaled to use maybe 90 % of the available screen estate - in my vertically positioned monitor the current layout is not quite optimal. :) 

Currently the window only shows about 2 lines of the table at a time. Sometimes it would be good to test minor changes directly in the browser, but the small window makes this quite inconvenient. 

![table editor window too small - screencapture-campaign-logger-1507029224146](https://user-images.githubusercontent.com/30939996/31122710-8c9eac9c-a845-11e7-9b44-cd3a21583040.png)

**Comment by JochenLinnemann** [comment]
Will be resolved with the new UI on which we are working currently .

**Comment by evesala** [comment]
Good to know! And the window sizing is already now better than it originally was.
