### ISSUE TITLE
Feature request: concatenating string variables

### ISSUE THREAD

**Issue by evesala** [open-campaign-logger/generator-library#22]
Many of my generators contain terms that may not be familiar to the reader, or otherwise would benefit from a bit longer explanation. 

For now I have included the explanations in parenthesis (like this), but with longer generator output *this can become cumbersome (as one might expect) especially if multiple explanations are included (in the same resultPattern) (like this).*
 
One solution is to use a *footnote* property that results requiring an explanation will write to. But in order to be useful, the system would need to be able to add to the already existing variable instead of overwriting it. 

Of course footnotes would not be the only way to use concatenated strings. They could be useful for example when generating lists of items or persons that could be later repeated in a different context.

**Comment by JochenLinnemann** [comment]
Have you tested set: { "x": "{var:x} new text" }?

**Comment by evesala** [comment]
This old issue can indeed be solved with the current functionality, thanks for the reminder! 

Closing this outdated ticket.
