### ISSUE TITLE
Generator Guide

### ISSUE THREAD

**Issue by psotos** [open-campaign-logger/generator-library#33]
The generator guide that I updated, was pushed to the Developer branch. The problem is that the Wiki section of this Github repo (https://github.com/open-campaign-logger/generator-library/wiki), points to the master branch. Can we merge that change to master?

**Comment by evesala** [comment]
I did merge the developer branch to the master, but did not remember that on the Wiki front page there was a link to a static copy of the Crash Course section of the Generator Guide document. (I added that just to get some content to the then-empty Wiki.) 

I have now replaced the static content with a link to the repository version, which indeed makes much more sense. Kudos for noticing the problem!

**Comment by psotos** [comment]
This is why they pay me the big bucks! LOL

**Comment by evesala** [comment]
I'll close this ticket as the issue was solved. Thanks for noticing the problem!
