### ISSUE TITLE
Adding white space to generated content

### ISSUE THREAD

**Issue by hkokko** [open-campaign-logger/generator-library#6]
How do I add whitespace on the  "resultPattern": "{event}  Temperature {MonsterIslandJungleTemperature} degrees Centigrade.  {MonsterIslandWeatherRainySeason}  " Would like to have for example line feeds or carriage returns to separate here for example event and temperature and centigrade and rainy season...

**Comment by JochenLinnemann** [comment]
This is implemented by now. You can use "\r\n" to add line feeds. In the preview this will render to <br />.
